# Generated by Django 5.1.4 on 2025-01-05 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_pin_created_at_user_wallet_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='wallet_pin',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
